### ISSUE TITLE
Ability Description Question

### ISSUE THREAD

**Issue by pil0lo** [TisRyno/LethalProgression#25]
Health Regeneration = resilience
Stamina = how long can you run
Battery Life = Time spent using electrical appliances such as pro flashlights
Hand Slots = weight of the item
Loot Value = the value of the item
Oxygen = ????
Strength = ????
Jump Height = Maximum height when jumping

------------------------------------------------------------
Is there a maximum LV?

**Comment by chibranche** [comment]
Your description is not correct.

Health Regeneration is how much health you get back every second
Hand Slots give you additional slots to carry items 
Oxygen is how much time you  can spend underwater without dying
Strength is the weight of the items

There is a configurable maximum level for each ability, no max overall level.
