### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CaraMob323** [TisRyno/LethalProgression#8]
**Mod Version**
v1.3.2

**Describe the bug**
I dont know

**To Reproduce**
1. Open Lethal

**Expected behavior**
Error in the console

**Screenshots**
[Error  : Unity Log] MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "LethalProgression.Properties.Resources.resources" was correctly embedded or linked into assembly "LethalProgression" at compile time, or that all the satellite assemblies required are loadable and fully signed.
Stack trace:
System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing (System.String fileName) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet (System.Globalization.CultureInfo culture, System.Collections.Generic.Dictionary`2[TKey,TValue] localResourceSets, System.Boolean tryParents, System.Boolean createIfNotExists, System.Threading.StackCrawlMark& stackMark) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo requestedCulture, System.Boolean createIfNotExists, System.Boolean tryParents, System.Threading.StackCrawlMark& stackMark) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo culture, System.Boolean createIfNotExists, System.Boolean tryParents) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Resources.ResourceManager.GetObject (System.String name, System.Globalization.CultureInfo culture, System.Boolean wrapUnmanagedMemStream) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Resources.ResourceManager.GetObject (System.String name, System.Globalization.CultureInfo culture) (at <787acc3c9a4c471ba7d971300105af24>:0)
LethalProgression.Properties.Resources.get_skillmenu () (at <a5e81e65909a464f827b0f12f481c832>:0)
LethalProgression.LethalPlugin.Awake () (at <a5e81e65909a464f827b0f12f481c832>:0)
UnityEngine.GameObject:DMD<UnityEngine.GameObject::AddComponent>(GameObject, Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.InputSystem.InputSystem:.cctor()

**Comment by TisRyno** [comment]
Hi @CaraMob323 

Thanks for your bug report, I am actively working to resolve this bug, along with a few others that have occurred.

This specific bug refers to the compilation process in which the https://github.com/TisRyno/LethalProgression/blob/main/LethalProgression/Properties/Resources.resx file does not seem to be picking up the skillmenu asset bundle.

Unfortunately as the Asset bundle has never been made publicly available for me to recompile it, all I can do is attempt workarounds.

I am hoping to have this fixed either today or tomorrow - I was fixing the mod originally for a streamer to use it on Sunday.

**Comment by TisRyno** [comment]
@CaraMob323 

I have released v1.6.0 - this should now fix all the issues, including a visual glitch on the pause menu where the `20 / 40` was showing under the XP progress bar.
